// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type BaseResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type Empty struct {
}

type EmptyResponse struct {
	BaseResponse
	Data Empty `json:"data"`
}

type ListMeta struct {
	Total int64 `json:"total"`
	Page  int64 `json:"page"`
	Size  int64 `json:"size"`
}

type PingRequest struct {
}

type PingResponse struct {
	Message string `json:"message"`
}
