// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	health "github.com/zevinto/go-zero-template/internal/handler/health"
	"github.com/zevinto/go-zero-template/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 健康检查
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: health.PingHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
